### ISSUE TITLE
Sourmash ANI estimate in some cases does not match manual computation, although using the same sketch signature

### ISSUE THREAD

**Issue by mahmudhera** [mahmudhera/sourmash-ani-implementation-test#1]
Running the script `python main.py inputs/ecoli.fasta --seed 0 --scalef 0.01` produces the results in the file [ani_comparison_results](https://github.com/mahmudhera/sourmash-ani-implementation-test/blob/main/ani_comparison_results). The results show a disagreement between manual calculation of the point estimate, and the sourmash estimate when the true ANI is <= 66%.

**Comment by mahmudhera** [comment]
@bluegenes is this because of some checks of the sketch size or the likelihood of corner cases? Please note that I do not use the `latest` branch of sourmash, rather compute the ANI using `sourmash compare --containment --estimate-ani` (please take a look at [this](https://github.com/mahmudhera/sourmash-ani-implementation-test/blob/main/utils/ani_by_sourmash.py)), and then take an average of the two ANI values.
@dkoslicki these may be of interest to you.

**Comment by bluegenes** [comment]
Hi @mahmudhera,

The `latest` sourmash addresses some issues with thresholding from your original equations that were affecting results (see https://github.com/sourmash-bio/sourmash/pull/2060). While I would recommend switching to `latest` to take advantage of this fix, I don't think that's the crux of the issue here.

I think the issue you're seeing is related to https://github.com/sourmash-bio/sourmash/issues/2003, where we zero out the ANI when the sketch size estimation may be inaccurate. I've been noticing the same thing that you're seeing here -- this is happening quite often (see https://github.com/sourmash-bio/sourmash/issues/2058 to see the original verbose output from these checks).

Are we being too strict with size accuracy estimation checks?
https://github.com/sourmash-bio/sourmash/blob/latest/src/sourmash/minhash.py#L942-L956

**Comment by mahmudhera** [comment]
Hi @bluegenes, I have rerun the script with the `latest` branch that I installed a few days ago for Phylo-ani. Strangely, there is now a perfect agreement between our estimate and the sourmash estimate of ANI ([see here](https://github.com/mahmudhera/sourmash-ani-implementation-test/blob/01b08d78ceb0f0d961775917fef2f963f9d85715/ani_comparison_results)). I am currently using the version 4.4.1.dev3+g99c3997 now, which uses 0.95 and 0.05 as parameters in the cardinality estimation function.

Therefore, just for the discrepancies in this repository (which can be seen [here](https://github.com/mahmudhera/sourmash-ani-implementation-test/blob/3b580c86610c5a1ef9bc0fe3a8ea72c6f169df67/ani_comparison_results)), I believe the issue is the hardcoded thresholds, not the size estimation being too stringent).
